### ISSUE TITLE
提示一个错误

### ISSUE THREAD

**Issue by supersnsd** [dclemon/APEX_YOLOV5_aimbot#1]
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\APEX_YOLOV5_aimbot-main\apex - 公开版.py
Traceback (most recent call last):
  File "C:\APEX_YOLOV5_aimbot-main\apex - 公开版.py", line 1, in <module>
    from jd_config import read_ini
ModuleNotFoundError: No module named 'jd_config'

**Comment by dclemon** [comment]
这个是读取配置项相关的，找到引用的部分删掉然后写在脚本里就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dclemon/APEX_YOLOV5_aimbot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月16日(星期五) 凌晨4:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dclemon/APEX_YOLOV5_aimbot] 提示一个错误 (Issue #1)





 
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
 Type "help", "copyright", "credits" or "license()" for more information.
 
= RESTART: C:\APEX_YOLOV5_aimbot-main\apex - 公开版.py
 Traceback (most recent call last):
 File "C:\APEX_YOLOV5_aimbot-main\apex - 公开版.py", line 1, in 
 from jd_config import read_ini
 ModuleNotFoundError: No module named 'jd_config'
